
#ifndef __ZMPI_TOOLS_CONF_H__
#define __ZMPI_TOOLS_CONF_H__


#define HAVE_ZMPI_ALLTOALL_2STEP
#define HAVE_ZMPI_ALLTOALLX_ISENDIRECV
#define HAVE_ZMPI_ALLTOALLX_SENDRECV
#define HAVE_ZMPI_ALLTOALLX_PROCLISTS
#define HAVE_ZMPI_ALLTOALL_INT
#define HAVE_ZMPI_REDUCE_SCATTER_BLOCK
#define HAVE_ZMPI_REDUCE_SCATTER_BLOCK_INTSUM


#endif /* __ZMPI_TOOLS_CONF_H__ */
